- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy Nginx config
  template:
    src: flask_proxy.conf.j2
    dest: /etc/nginx/sites-available/flask_proxy

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/flask_proxy
    dest: /etc/nginx/sites-enabled/flask_proxy
    state: link
    force: yes

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
